export const REGIONS: { [key: string]: string } = {
  all: '모든 지역',
  seoul: '서울',
  busan: '부산',
  daegu: '대구',
  incheon: '인천',
  gwangju: '광주',
  daejeon: '대전',
  ulsan: '울산',
  sejong: '세종',
  gyeonggi: '경기',
  gangwon: '강원',
  chungcheongbuk: '충북',
  chungcheongnam: '충남',
  jeollabuk: '전북',
  jeollanam: '전남',
  gyeongsangbuk: '경북',
  gyeongsangnam: '경남',
  jeju: '제주',
};
