export const REGIONS: { [key: string]: string } = {
  All: '모든 지역',
  Seoul: '서울',
  Busan: '부산',
  Daegu: '대구',
  Incheon: '인천',
  Gwangju: '광주',
  Daejeon: '대전',
  Ulsan: '울산',
  Sejong: '세종',
  Gyeonggi: '경기',
  Gangwon: '강원',
  Chungcheongbuk: '충북',
  Chungcheongnam: '충남',
  Jeollabuk: '전북',
  Jeollanam: '전남',
  Gyeongsangbuk: '경북',
  Gyeongsangnam: '경남',
  Jeju: '제주',
};
